#!/bin/sh
#
# Change permissions on /dev/ugenN.EE
#

event="$1"
shift
devices=$@

# list of VIP:PID for NFC readers
IDS="
04cc:0531
054c:0193
04cc:2533
072f:2200
1fd3:0608
04e6:5591
"

CHKUGENIDS=/usr/pkg/sbin/chkugenids

for device in $devices; do
	case $device in
	ugen*)
		case $event in
		device-attach)
			echo "NFCsetperm: $device attached"
			DEVID=`$CHKUGENIDS -f /dev/$device.00 -i -q`
			for i in $IDS
			do
				if [ "$DEVID" = "$i" ]
				then
					logger -s "NFCsetperm: device match. Adjusting permissions for /dev/$device.*"
					chmod g+rw /dev/$device.*
				fi
			done
			;;
		device-detach)
			logger -s "NFCsetperm: $device detached. Setting back permissions on /dev/$device.*"
			chmod 600 /dev/$device.*
			;;
		esac
		;;
	esac
done

